"""MeadowClient — the client-side Socket.IO transport for MEADOWS.

This wraps `socketio.AsyncClient` with:
  - JWT handshake on /chat namespace connect
  - Auto-reconnect (delegated to socketio's reconnection logic)
  - A typed `send_message()` that constructs the protocol envelope
  - Event-handler registration via `on(event, handler)`

It contains no domain logic. Bots and UIs built on top register their
own handlers; this client only ensures the wire-level contract holds.

Key invariant: this client never sends a frame that violates
`meadows.protocol`. The `send_message()` method constructs a valid
`Message` before emitting, so the chokepoint on the server side never
sees an invalid frame from us.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from typing import Any, Awaitable, Callable

import socketio

from meadows.protocol import EventName, JWTClaims, Label, Message, MessageType
from meadows.protocol.envelope import generate_message_id
from meadows.protocol.jwt import ALGORITHM

import jwt as pyjwt

logger = logging.getLogger(__name__)

Handler = Callable[[dict[str, Any]], Awaitable[None] | None]
ConnectHandler = Callable[[], Awaitable[None] | None]


class MeadowClientError(Exception):
    """Raised when the client cannot start or a transport-level error occurs."""


class MeadowClient:
    """Async Socket.IO client for MEADOWS, with JWT handshake.

    BUSINESS RULE: only the server knows the signing key. Clients use a
    pre-signed JWT (generated by the server via ``inv bot-jwt`` or
    ``inv user-jwt``). The ``token`` parameter is the primary auth path;
    ``jwt_secret`` exists only for backward compatibility (e.g. the TUI's
    secret-path flow).

    Usage:
        client = MeadowClient(
            server_url="http://localhost:8080",
            claims=build_claims(name="alice", role=JWTRole.USER),
            token="<pre-signed-jwt>",
        )
        client.on(EventName.MESSAGE, handle_message)
        await client.connect()
        await client.send_message(content="hello", group_id="general")
    """

    NAMESPACE = "/chat"

    def __init__(
        self,
        *,
        server_url: str,
        claims: JWTClaims,
        jwt_secret: bytes = b"",
        token: str | None = None,
        socketio_client: socketio.AsyncClient | None = None,
    ) -> None:
        self.server_url = server_url
        self.claims = claims
        self.jwt_secret = jwt_secret
        self.token = token

        self.sio: socketio.AsyncClient = socketio_client or socketio.AsyncClient(
            reconnection=True,
            reconnection_attempts=None,
            reconnection_delay=1,
            reconnection_delay_max=10,
            logger=False,
            engineio_logger=False,
        )

        self._connected = False
        self._authenticated = False
        self._handlers: dict[EventName, Handler] = {}
        self._connect_handlers: list[ConnectHandler] = []
        self._disconnect_handlers: list[ConnectHandler] = []
        self._label_subscriptions: list[dict[str, Any]] = []  # for replay on reconnect
        self._label_assigned_handlers: dict[str, Handler] = {}  # subscription_name → callback
        self._pending_rpc_futures: dict[str, asyncio.Future[str]] = {}  # request_id → Future for call_rpc
        self._pending_tasks: list[asyncio.Task[None]] = []

        self._register_internal_handlers()

    @property
    def connected(self) -> bool:
        return self._connected

    @property
    def authenticated(self) -> bool:
        return self._authenticated

    def on(self, event: EventName | str, handler: Handler) -> None:
        """Register a handler for an event on the /chat namespace.

        BUSINESS RULE: python-socketio's on() replaces existing handlers
        (dict assignment, not append). The client has internal handlers
        for AUTHENTICATED, BOT_AUTHENTICATED, AUTH_ERROR, and ERROR that
        must always run (they set connection state). If a user registers
        a handler for the same event, we chain: internal handler runs
        first, then the user's handler. This prevents a bot's
        on_bot_authenticated from silently overriding the client's
        _on_authenticated (which sets the authenticated flag).
        """
        name = event.value if isinstance(event, EventName) else str(event)
        self._handlers[EventName(name) if name in {e.value for e in EventName} else name] = handler  # type: ignore[arg-type]

        # Chain with any existing handler (internal or user-registered).
        existing = None
        sio_handlers = getattr(self.sio, "handlers", None)
        if sio_handlers is not None:
            ns_handlers = sio_handlers.get(self.NAMESPACE, {})
            if name in ns_handlers:
                existing = ns_handlers[name]
        else:
            # FakeAsyncClient (tests) — check _handlers dict
            for (evt, _ns), h in getattr(self.sio, "_handlers", {}).items():
                if evt == name:
                    existing = h
                    break

        if existing is None:
            self.sio.on(name, handler, namespace=self.NAMESPACE)
        else:

            async def chained(_data: dict[str, Any]) -> None:
                result = existing(_data)
                if hasattr(result, "__await__"):
                    await result
                result = handler(_data)
                if hasattr(result, "__await__"):
                    await result

            self.sio.on(name, chained, namespace=self.NAMESPACE)

    def on_connect(self, handler: ConnectHandler) -> None:
        """Register a handler fired when /chat namespace connects (post-auth)."""
        self._connect_handlers.append(handler)

    def on_disconnect(self, handler: ConnectHandler) -> None:
        """Register a handler fired when /chat namespace disconnects."""
        self._disconnect_handlers.append(handler)

    def _register_internal_handlers(self) -> None:
        self.sio.on("connect", self._on_namespace_connect, namespace=self.NAMESPACE)
        self.sio.on("disconnect", self._on_namespace_disconnect, namespace=self.NAMESPACE)
        self.sio.on(
            EventName.BOT_AUTHENTICATED.value,
            self._on_authenticated,
            namespace=self.NAMESPACE,
        )
        self.sio.on(
            EventName.AUTHENTICATED.value,
            self._on_authenticated,
            namespace=self.NAMESPACE,
        )
        self.sio.on(EventName.AUTH_ERROR.value, self._on_auth_error, namespace=self.NAMESPACE)
        self.sio.on(EventName.ERROR.value, self._on_error, namespace=self.NAMESPACE)
        self.sio.on(EventName.LABEL_ASSIGNED.value, self._on_label_assigned_event, namespace=self.NAMESPACE)
        # Async RPC: resolve futures when RPC_RESPONSE arrives.
        self.sio.on(EventName.MESSAGE.value, self._on_rpc_response_message, namespace=self.NAMESPACE)

    async def _on_namespace_connect(self) -> None:
        """On /chat connect, send the authenticate event with our JWT.

        If a pre-signed ``token`` was provided at construction, it is
        sent directly. Otherwise the token is signed locally using
        ``jwt_secret`` (legacy path).
        """
        logger.debug("SIO /chat connected — emitting authenticate event")
        if self.token:
            token = self.token
        elif self.jwt_secret:
            token = pyjwt.encode(
                self.claims.model_dump(exclude_none=True),
                self.jwt_secret,
                algorithm=ALGORITHM,
            )
        else:
            raise MeadowClientError(
                "No authentication token available. "
                "Pass a pre-signed JWT via the `token` parameter "
                "or set the MEADOWS_JWT_TOKEN environment variable."
            )
        await self.sio.emit(
            EventName.AUTHENTICATE.value,
            {"token": token},
            namespace=self.NAMESPACE,
        )
        logger.debug("authenticate event emitted, waiting for server response...")

    async def _on_namespace_disconnect(self) -> None:
        self._connected = False
        self._authenticated = False
        logger.debug("SIO /chat disconnected")
        for handler in self._disconnect_handlers:
            result = handler()
            if hasattr(result, "__await__"):
                await result

    async def _on_authenticated(self, _data: dict[str, Any]) -> None:
        self._connected = True
        self._authenticated = True
        logger.debug("authenticated as %s", self.claims.name())
        for handler in self._connect_handlers:
            result = handler()
            if hasattr(result, "__await__"):
                await result
        # Replay label subscriptions after reconnect
        for sub_data in self._label_subscriptions:
            await self.emit(EventName.REGISTER_LABEL_SUBSCRIPTION, sub_data)

    async def _on_auth_error(self, data: dict[str, Any]) -> None:
        self._authenticated = False
        logger.error("auth error from server: %s", data)
        raise MeadowClientError(f"authentication failed: {data}")

    async def _on_error(self, data: dict[str, Any]) -> None:
        logger.error("server error: %s", data)

    async def connect(self) -> None:
        """Connect to the server and start the background receiver.

        Returns once the transport is connected; auth completes
        asynchronously via the `_on_authenticated` handler.
        """
        logger.debug("sio.connect(%s, namespaces=['/chat'], transports=['websocket'])", self.server_url)
        try:
            await self.sio.connect(
                self.server_url,
                namespaces=[self.NAMESPACE],
                transports=["websocket"],
            )
            logger.debug("sio.connect() returned — transport established")
        except Exception as exc:
            logger.error("sio.connect() failed: %s: %s", type(exc).__name__, exc)
            raise MeadowClientError(f"failed to connect to {self.server_url}: {exc}") from exc

    async def disconnect(self) -> None:
        """Disconnect from the server."""
        self._connected = False
        self._authenticated = False
        await self.sio.disconnect()

    async def wait(self) -> None:
        """Block until the client disconnects."""
        await self.sio.wait()

    async def send_message(
        self,
        *,
        content: str,
        group_id: str = "general",
        quoted_message_id: str | None = None,
    ) -> Message:
        """Send a chat message. Returns the constructed Message.

        The Message is constructed via the protocol envelope so the wire
        form is always valid — the server-side chokepoint never sees an
        invalid frame from us.
        """
        from meadows.protocol.envelope import QuotedMessage, generate_message_id, now_iso

        quoted = None
        if quoted_message_id:
            quoted = QuotedMessage(
                id=quoted_message_id,
                author=self.claims.name(),
                content="",
                timestamp=now_iso(),
            )

        msg = Message(
            id=generate_message_id(),
            type=MessageType.USER if self.claims.is_user() else MessageType.BOT,
            user_id=self.claims.sub,
            username=self.claims.username,
            bot_name=self.claims.bot_name,
            group_id=group_id,
            content=content,
            quoted_message=quoted,
        )

        await self.sio.emit(
            EventName.MESSAGE.value,
            msg.model_dump(exclude_none=True),
            namespace=self.NAMESPACE,
        )
        return msg

    def register_label_subscription(
        self,
        name: str,
        predicate: dict[str, Any] | None = None,
        scope: str = "room",
        group_id: str | None = None,
        deliver: str = "label_only",
    ) -> None:
        """Register a label subscription with the server.

        BUSINESS RULE (MEADOWS-labeling-intent §2.4): subscriptions live in
        meadows-client, not meadows-bot.  Both bots and GUI/TUI clients
        need this.  The client is the transport layer.

        Stores locally for replay on reconnect.
        """
        data: dict[str, Any] = {"name": name, "predicate": predicate or {}, "scope": scope, "deliver": deliver}
        if group_id:
            data["group_id"] = group_id
        self._label_subscriptions.append(data)
        try:
            loop = asyncio.get_running_loop()
            self._pending_tasks: list[asyncio.Task[None]] = getattr(self, "_pending_tasks", [])
            task = loop.create_task(self.emit(EventName.REGISTER_LABEL_SUBSCRIPTION, data))
            self._pending_tasks.append(task)
        except RuntimeError:
            pass  # not in async context — will replay on connect

    def unregister_label_subscription(self, name: str) -> None:
        """Remove a label subscription by name."""
        self._label_subscriptions = [s for s in self._label_subscriptions if s["name"] != name]
        try:
            loop = asyncio.get_running_loop()
            self._pending_tasks: list[asyncio.Task[None]] = getattr(self, "_pending_tasks", [])
            task = loop.create_task(self.emit(EventName.UNREGISTER_LABEL_SUBSCRIPTION, {"name": name}))
            self._pending_tasks.append(task)
        except RuntimeError:
            pass

    def on_label_assigned(self, name: str) -> Callable:
        """Decorator: register callback for label_assigned events.

        BUSINESS RULE (MEADOWS-labeling-intent §2.4): ``on_label_assigned()``
        lives in meadows-client so both bots and UI clients can use it.
        """

        def decorator(func: Handler) -> Handler:
            self._label_assigned_handlers[name] = func
            return func

        return decorator

    async def _on_label_assigned_event(self, data: dict[str, Any]) -> None:
        """Internal: dispatch label_assigned events to registered handlers."""
        sub_name = data.get("subscription_name")
        if sub_name and sub_name in self._label_assigned_handlers:
            handler = self._label_assigned_handlers[sub_name]
            result = handler(data)
            if hasattr(result, "__await__"):
                await result

    def _on_rpc_response_message(self, data: dict[str, Any]) -> None:
        """Internal: resolve futures when an RPC_RESPONSE arrives.

        BUSINESS RULE (§2.10): runs on every MESSAGE event.  Checks
        for RPC_RESPONSE type, extracts request_id from label metadata,
        and resolves the matching Future created by call_rpc().
        """
        if data.get("type") != MessageType.RPC_RESPONSE.value:
            return

        labels = data.get("labels", [])
        request_id = None
        for lbl in labels:
            if isinstance(lbl, (list, tuple)) and len(lbl) > 3 and isinstance(lbl[3], dict):
                request_id = lbl[3].get("request_id")
                if request_id:
                    break

        if not request_id:
            return

        fut = self._pending_rpc_futures.pop(request_id, None)
        if fut and not fut.done():
            fut.set_result(data.get("content", ""))

    async def call_rpc(
        self,
        service_label: str,
        content: str,
        *,
        origin: str | None = None,
        semver: str = "1.0.0",
        timeout: float = 30.0,
        group_id: str = "general",
    ) -> str:
        """Send an RPC request and await the response.

        BUSINESS RULE (§2.10): this is the async author surface for
        RPC across all client types — bots, TUI, GUI.  It sends an
        RPC_REQUEST, creates an asyncio.Future, and resolves it when
        the matching RPC_RESPONSE arrives.

        Must be called from an async context.

        Args:
            service_label: The service label to route to (e.g. "service:math").
            content: The request payload.
            origin: Label origin. Defaults to caller's bot_name or sub.
            semver: Label semver. Defaults to "1.0.0".
            timeout: Seconds to wait for a response. Default 30.
            group_id: Group to persist the request/response in.

        Returns:
            The response content string.

        Raises:
            asyncio.TimeoutError: if no response arrives within *timeout*.
        """
        request_id = uuid.uuid4().hex[:12]
        origin = origin or self.claims.bot_name or self.claims.sub
        meta = {"request_id": request_id}
        msg = Message(
            id=generate_message_id(),
            type=MessageType.RPC_REQUEST,
            user_id=self.claims.sub,
            bot_name=self.claims.bot_name,
            group_id=group_id,
            content=content,
            labels=[Label(origin, service_label, semver, meta)],
        )
        await self.emit(EventName.MESSAGE, msg.model_dump(exclude_none=True))

        loop = asyncio.get_running_loop()
        future: asyncio.Future[str] = loop.create_future()
        self._pending_rpc_futures[request_id] = future

        try:
            return await asyncio.wait_for(future, timeout=timeout)
        except asyncio.TimeoutError:
            self._pending_rpc_futures.pop(request_id, None)
            raise

    async def emit(self, event: EventName | str, data: Any) -> None:
        """Emit a raw event. Use sparingly — prefer send_message() for chat.

        This is the escape hatch for events the client sends that aren't
        ordinary messages (e.g. typing, add_reaction). The caller is
        responsible for the shape of `data`.
        """
        name = event.value if isinstance(event, EventName) else str(event)
        await self.sio.emit(name, data, namespace=self.NAMESPACE)


__all__ = ["MeadowClient", "MeadowClientError"]
